import { useCallback, useState, type ReactNode } from 'react';
import { useAdminApi, useAdminQuery } from './AdminApiContext';
import { AdminEmptyState, AdminErrorState, AdminLoadingState, AdminPageHeader, formatAdminDate } from './AdminPageState';

function Bytes({ value }: { readonly value: number }) { return <>{new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 1, notation: 'compact' }).format(value)} o</>; }
function PageData<T>({ state, children }: { readonly state: ReturnType<typeof useAdminQuery<T>>['state']; readonly children: (data: T) => ReactNode }) { if (state.kind === 'loading') return <AdminLoadingState />; if (state.kind === 'error') return <AdminErrorState error={state.error} />; return <>{children(state.data)}</>; }

export function AdminAuditPage() {
  const api = useAdminApi(); const [draft, setDraft] = useState({ action: '', targetId: '' }); const [filters, setFilters] = useState(draft);
  const load = useCallback((options: { signal?: AbortSignal }) => api.listGlobalAudit(filters, options), [api, filters]); const { state, reload } = useAdminQuery(load, [load]);
  return <section><AdminPageHeader title="Audit global" actions={<button className="button button--secondary" type="button" onClick={reload}>Actualiser</button>}><p>Journal append-only des décisions. Les snapshots, payloads et contenus bruts ne sont jamais exposés dans cette vue.</p></AdminPageHeader><form className="admin-filter-row" onSubmit={(event) => { event.preventDefault(); setFilters(draft); }}><label>Action<input value={draft.action} maxLength={128} onChange={(event) => setDraft((value) => ({ ...value, action: event.target.value }))} placeholder="incident.transition" /></label><label>Cible<input value={draft.targetId} maxLength={128} onChange={(event) => setDraft((value) => ({ ...value, targetId: event.target.value }))} placeholder="FR-83-00042" /></label><button className="button button--small" type="submit">Filtrer</button></form><PageData state={state}>{(events) => events.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Quand</th><th>Action</th><th>Cible</th><th>Acteur</th><th>Motif</th><th>Trace</th></tr></thead><tbody>{events.map((event) => <tr key={event.event_id}><td>{formatAdminDate(event.occurred_at)}</td><th scope="row"><code>{event.action}</code></th><td>{event.target_type} <code>{event.target_id}</code></td><td>{event.actor_type} / {event.actor_id}</td><td>{event.reason}</td><td><code>{event.trace_id}</code></td></tr>)}</tbody></table></div> : <AdminEmptyState title="Aucun événement">Aucun événement ne correspond aux filtres courants.</AdminEmptyState>}</PageData></section>;
}

export function AdminRolesPage() { const api = useAdminApi(); const load = useCallback((options: { signal?: AbortSignal }) => api.getRoles(options), [api]); const { state } = useAdminQuery(load, [load]); return <section><AdminPageHeader title="Accès administrateur"><p>Cette instance utilise un compte administrateur local unique. Aucun rôle, compte ou secret n’est géré depuis le navigateur.</p></AdminPageHeader><PageData state={state}>{(roles) => <section className="admin-detail-card"><h3>Session courante</h3><dl><div><dt>Acteur</dt><dd><code>{roles.actor_id}</code></dd></div><div><dt>Type</dt><dd>{roles.actor_type}</dd></div><div><dt>Gestion d’identité</dt><dd>{roles.identity_management}</dd></div></dl><p>Capacités du compte local : {roles.assigned_roles.join(' · ')}.</p></section>}</PageData></section>; }

export function AdminSystemPage() { const api = useAdminApi(); const load = useCallback((options: { signal?: AbortSignal }) => api.getSystemStatus(options), [api]); const { state, reload } = useAdminQuery(load, [load]); return <section><AdminPageHeader title="État système" actions={<button className="button button--secondary" type="button" onClick={reload}>Actualiser</button>}><p>État observé à la demande. L’absence de heartbeat ne signifie jamais qu’un worker fonctionne.</p></AdminPageHeader><PageData state={state}>{(system) => <><div className="admin-status-grid"><article><h3>Application</h3><p>{system.application.name} {system.application.version}</p><strong>{system.application.environment}</strong><small>Authentification : {system.application.authentication_mode}</small></article><article><h3>Base</h3><p>{system.database.reachable ? 'Accessible' : 'Indisponible'}</p><strong>{system.database.dialect}</strong><small>Contrôlée le {formatAdminDate(system.checked_at)}</small></article><article><h3>Workers</h3><p>Heartbeat : {system.worker_heartbeat}</p><small>Aucun statut de worker n’est déduit sans signal persistant.</small></article><article><h3>Audit</h3><p><strong>{system.audit_event_count}</strong> événement(s)</p></article></div><section className="admin-section"><div className="admin-section__heading"><div><h3>Files</h3></div></div><dl className="admin-metric-grid"><div><dt>Jobs actifs</dt><dd>{system.queues.jobs_active}</dd></div><div><dt>Jobs quarantainés</dt><dd>{system.queues.jobs_quarantined}</dd></div><div><dt>Outbox en attente</dt><dd>{system.queues.outbox_pending}</dd></div><div><dt>Outbox en erreur</dt><dd>{system.queues.outbox_with_error}</dd></div><div><dt>Signalements ouverts</dt><dd>{system.queues.reports_pending}</dd></div></dl></section><section className="admin-section"><div className="admin-section__heading"><div><h3>Packages spatiaux</h3></div></div><dl className="admin-metric-grid"><div><dt>Brouillons</dt><dd>{system.assets.packages_draft}</dd></div><div><dt>Vérifiés</dt><dd>{system.assets.packages_verified}</dd></div><div><dt>Prévisualisables</dt><dd>{system.assets.packages_previewable}</dd></div><div><dt>Publiés</dt><dd>{system.assets.packages_published}</dd></div><div><dt>Retirés ou révoqués</dt><dd>{system.assets.packages_withdrawn_or_revoked}</dd></div></dl></section></>}</PageData></section>; }

export function AdminConfigurationPage() { const api = useAdminApi(); const load = useCallback((options: { signal?: AbortSignal }) => api.getConfiguration(options), [api]); const { state } = useAdminQuery(load, [load]); return <section><AdminPageHeader title="Configuration"><p>Projection sûre, strictement en lecture seule. Les changements de déploiement, secrets et politiques d’identité restent hors de l’interface.</p></AdminPageHeader><PageData state={state}>{(configuration) => <><div className="admin-status-grid"><article><h3>Déploiement</h3><p>{configuration.environment}</p><small>Authentification : {configuration.authentication_mode}</small><small>{configuration.identity_management}</small></article><article><h3>Signalement public</h3><p>{configuration.public.report_rate_limit_per_day} / jour</p><small>Rétention idempotence : {configuration.public.idempotency_retention_hours} h</small></article><article><h3>Archives</h3><p><Bytes value={configuration.storage.archive_max_bytes} /></p><small>Décompressé : <Bytes value={configuration.storage.unpacked_max_bytes} /></small></article></div><section className="admin-section"><div className="admin-section__heading"><div><h3>Rapprochement spatial</h3><p>Politique {configuration.matching.policy_id}</p></div></div><dl className="admin-metric-grid"><div><dt>Créer sous</dt><dd>{configuration.matching.create_below}</dd></div><div><dt>Attacher au-dessus</dt><dd>{configuration.matching.auto_attach_above}</dd></div><div><dt>Marge minimale</dt><dd>{configuration.matching.min_margin}</dd></div><div><dt>Distance maximale</dt><dd>{configuration.matching.max_candidate_distance_m.toLocaleString('fr-FR')} m</dd></div><div><dt>Incertitude maximale</dt><dd>{configuration.matching.max_incident_uncertainty_m.toLocaleString('fr-FR')} m</dd></div><div><dt>Candidats maximum</dt><dd>{configuration.matching.max_candidates}</dd></div></dl></section><section className="admin-detail-card"><h3>Notice publique</h3><p>{configuration.public.public_notice}</p></section></>}</PageData></section>; }
